version: '3'
services:
  py12306:
    container_name: py12306
    build: .
    image: py12306
    restart: always
    volumes:
      - ./runtime:/code/runtime  # 未使用 env.docker.py.example 可以打开此项
      - ./env.py:/config/env.py
    ports:
      - 8208:8208
    command: python main.py -c /config/env.py
